# Generated by Django 4.1.7 on 2023-02-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0002_produit_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='type',
            new_name='Type',
        ),
    ]
